steps:
  - id: 'Rodando docker compose'
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.25.5'
    args: ['-f', 'docker-compose-cloud-build.yaml', 'up', '-d']

  - id: 'Rodando docker ps'
    name: 'gcr.io/$PROJECT_ID/docker'
    args: ['ps']

  - id: 'Rodando compose'
    name: 'gcr.io/$PROJECT_ID/docker'
    args: ['exec', '-t', 'app', 'composer', 'install']