version: "3"

services:
  nginx:
    build: .docker/nginx
    container_name: nginx
#    entrypoint: dockerize -template ./.up/nginx.tmpl:/etc/nginx/conf.d/nginx.conf -wait tcp://app:9000 -timeout 40s nginx -g 'daemon off;'
#    environment:
#        - NGINX_PORT=80
#        - APP_HOST=app
#        - APP_PORT=9000
    restart: always
    tty: true
    ports:
    - "8000:80"
    volumes:
    - ./app:/var/www
    networks:
      - app-networks
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: my_redis
    expose:
      - 6379
    networks:
      - app-networks

  app:
    build: .
    container_name: app
    entrypoint: dockerize -template ./.up/.env:.env -wait tcp://db:3306 -timeout 40s ./.up/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

    volumes:
    - ./app:/var/www
    networks:
      - app-networks
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
    - "3306:3306"
    volumes:
    - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge