version: "3"

services:
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
    - "8000:80"
    volumes:
    - ./app:/var/www
    networks:
      - app-networks

  redis:
    image: redis:alpine
    container_name: my_redis
    expose:
      - 6379
    networks:
      - app-networks

  app:
    build: .
    container_name: app
    volumes:
    - ./app:/var/www
    networks:
      - app-networks

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
    - "3306:3306"
    volumes:
    - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge